OBJS = miniServer.o miniClient.o
//SRCS = $(OBJS:.o=.c)
CC = gcc
CFLAGS = -c

all : miniServer miniClient
miniServer: miniServer.o
	$(CC) -o $@ miniServer.o
miniServer.o:
	$(CC) -c miniServer.c
miniClient: miniClient.o
	$(CC) -o $@ miniClient.o
	$(CC) -c miniClient.c

clean :
	rm *.o miniServer miniClient